USE StudentManagement;
GO

IF NOT EXISTS (
   SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
   WHERE TABLE_NAME = 'Students' AND COLUMN_NAME = 'MiddleName'
)
BEGIN
    ALTER TABLE Students ADD MiddleName NVARCHAR(50) NULL;
END
GO
