version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongPass123!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  sqlserver-data:
